Add support for destroy_data to be sent
Mastercard/terraform-provider-restapi pull request #182
Opened 2022-07-07 21:35 UTC by jgrumboe

2022-07-07 21:42 UTC, jgrumboe commented
@DRuggeri Is this PR ok? Is the test sufficient?

If it's fine I could also "extend" this PR to solve #124 and add `update_data` in the same way.

2022-07-21 08:15 UTC, m-garrido commented
It would be awesome to have the same feature for update and delete.

2022-08-16 05:20 UTC, jgrumboe commented
@m-garrido @melt-melt
I also added support for `update_data`.
@DRuggeri can you have a look at this?

2022-08-16 07:41 UTC, jgrumboe commented
@DRuggeri I needed to update the GH release action also following this comment https://github.com/hashicorp/ghaction-import-gpg/issues/11#issuecomment-1185107410
Otherwise I wasn't able to publish the provider interim to my personal TF registry account.

I can remove the commit before merging.

2022-08-16 07:56 UTC, jgrumboe commented
@m-garrido @melt-melt
I published my changes interim to TF registry under https://registry.terraform.io/providers/jgrumboe/restapi/1.18.0-dev
You could try out `update_data` and `destroy_data` for tests, would like to remove the provider from my account in the TF registry after this PR is merged.

2022-08-31 08:32 UTC, arun-a-nayagam reviewed
I have tested the update_data changes in an actual project and can confirm that it works fine.

2022-09-13 21:42 UTC, jgrumboe commented
@DRuggeri can you help me here to get that merged? If something is missing like tests or docs, just tell me. Thanks in advance 🙏

2022-10-23 16:58 UTC, jgrumboe commented
@douernesto @Martina-May 
Could you probably help in getting this PR merged? Unfortunately there's no feedback yet from @DRuggeri 😞

2022-10-26 12:51 UTC, Sh1ftry commented
Hello, I am also waiting for this feature. Would be nice to have it released soon.

2022-11-02 14:09 UTC, DRuggeri requested changes
This looks good, though I am concerned about some of the changes to the release workflow. Can you please address those?

2022-11-02 14:10 UTC, DRuggeri commented
Many apologies for the delay responding to this PR. This seems to make a lot of sense and I've added a quick few notes. If you can address those, we can go ahead and merge and cut a new release with this!

2022-11-02 15:21 UTC, jgrumboe commented on .github/workflows/release.yaml
> +        uses: crazy-max/ghaction-import-gpg@v5
This change is encouraged by one of hashicorp gh actions maintainer: https://github.com/hashicorp/ghaction-import-gpg/issues/11#issuecomment-1185107410
(also commented it here some time ago)

2022-11-02 15:28 UTC, jgrumboe commented on .github/workflows/release.yaml
> +          args: release --rm-dist
Fixed in 225bd5f

2022-11-02 15:28 UTC, jgrumboe commented on .github/workflows/release.yaml
> +# This uses an action (hashicorp/ghaction-import-gpg) that assumes you set your
Fixed in 225bd5f

2022-11-02 15:33 UTC, jgrumboe commented on restapi/api_object.go
> +	destroyData map[string]interface{} /* Update data as managed by the user */
Fixed in cb4ab82

2022-11-02 15:34 UTC, jgrumboe commented on docs/resources/object.md
> +- **update_data** (String, Optional) Valid JSON data that this provider will send to the API server on UPDATE (PUT) operations. Allows override of `data` on UPDATE (PUT) operations.
Fixed in cb4ab82

2022-11-02 15:34 UTC, jgrumboe commented on docs/resources/object.md
> +- **destroy_data** (String, Optional) Valid JSON data that this provider will send to the API server on DESTROY (DELETE) operations.
Fixed in cb4ab82

2022-11-02 15:34 UTC, jgrumboe commented
@DRuggeri Thanks for the feedback. I addressed it.

2022-11-02 16:57 UTC, DRuggeri commented on .github/workflows/release.yaml
> +        uses: crazy-max/ghaction-import-gpg@v5
Got it - thanks!

2022-11-02 16:59 UTC, DRuggeri approved these changes

2022-11-02 17:00 UTC, merged